# Gaussian Elimination with Backpropogation

### We can solve a system of equations by representing them as a matrix and using Gaussian Elimination with Backpropogation.

A common example of this in physics is solving for currents through circuit elements (resistors) using Kirchoff's Loop and Junction Rules.

The example shown below,
<img src="circuit.png" width="300">
Gives the equations: 

$$5I_1 - 3I_2 = 5$$ 
$$-3I_1 + 9I_2  - 6I_3= 4$$
$$-6I_2  + 10I_3= 1$$

This system of equations can be represented as a matrix equation of the form ${\bf Ax = b}$: 


$ 
\begin{bmatrix}
    5       & -3 & 0  \\
    -3       & 9 & -6  \\
    -6      & 0 & 10 
\end{bmatrix} 
$
$
 \begin{bmatrix}
    I_1      \\
    I_2      \\
    I_3    
\end{bmatrix}
$
=
$
\begin{bmatrix}
    5      \\
    4      \\
    1    
\end{bmatrix}
$

### 1) On a piece of paper, do the Gaussian Elimination for this problem by hand with your partner. 
### Treat this as a pair programming assignment. You will each take turns writing.

### 2) Next, we will look at the code to implement this method:
    a) Comment each line of the below code to indicate what it does
    b) Solve the same problem as above using the provided functions. 
    *Reminder: Matrices are 2D arrays, thus must be created with the numpy arrays.







In [3]:
def Gauss_Elim(A,b): #defining the gaussian elimination function.
    N = len(b) #setting a variable N to be equal to the length of the array "b"
    print(N) #printing N defined in the line above.
    for m in range(N): #iterate through each value of the array b
        div = A[m,m] #defining a variable div as the mth row and column in the array A
        b[m] /= div #dividing the mth value of b by the variable div defined above.
        A[m,:] /= div #dividing all the values in the mth row of array A by the variable div.
        for i in range(m+1,N):#iterate through the next value of b.
            mult = A[i,m]#define variable mult as the index of the ith row and mth column of the array A.
            b[i] -= mult*b[m]#subtract mult (defined above) times the mth index of b from the ith index of b.
            A[i,:] -= mult*A[m,:]#subtract mult times the mth row of A from the ith row of A.
    return A,b#returns matricies A and b once the code is completed


In [4]:
def Back_Sub(A,b): #defining a back substitution function
    N = len(b) #definnig N as the lenght of array b
    x = zeros(N,float) #defining x as an array of zeros with dimentions N x 1
    x[N-1] = b[N-1] #
    for m in range(N-1,-1,-1):
        x[m] = b[m]
        for i in range(m+1,N):
            x[m] -= A[m,i]*x[i]
    return x

In [5]:
from numpy import array, zeros
A = array([[5,-3,0],[-3,9,-6],[-6,0,10]],float)
print(A)
b = [5,4,1]
Aa, Bb = Gauss_Elim(A,b)
print(Back_Sub(Aa,Bb))

[[  5.  -3.   0.]
 [ -3.   9.  -6.]
 [ -6.   0.  10.]]
3
[ 2.33333333  2.22222222  1.5       ]


## Questions:
    1) What are the benefits of using the algorithm as opposed to solving by hand?
    2) How can this code fail?