# Gaussian Elimination with Backpropogation

### We can solve a system of equations by representing them as a matrix and using Gaussian Elimination with Backpropogation.

A common example of this in physics is solving for currents through circuit elements (resistors) using Kirchoff's Loop and Junction Rules.

The example shown below,
<img src="circuit.png" width="300">
Gives the equations: 

$$5I_1 - 3I_2 = 5$$ 
$$-3I_1 + 9I_2  - 6I_3= 4$$
$$-6I_2  + 10I_3= 1$$

This system of equations can be represented as a matrix equation of the form ${\bf Ax = b}$: 


$ 
\begin{bmatrix}
    5       & -3 & 0  \\
    -3       & 9 & -6  \\
    -6      & 0 & 10 
\end{bmatrix} 
$
$
 \begin{bmatrix}
    I_1      \\
    I_2      \\
    I_3    
\end{bmatrix}
$
=
$
\begin{bmatrix}
    5      \\
    4      \\
    1    
\end{bmatrix}
$

### 1) On a piece of paper, do the Gaussian Elimination for this problem by hand with your partner. 
### Treat this as a pair programming assignment. You will each take turns writing.

### 2) Next, we will look at the code to implement this method:
    a) Comment each line of the below code to indicate what it does
    b) Solve the same problem as above using the provided functions. 
    *Reminder: Matrices are 2D arrays, thus must be created with the numpy arrays.







In [8]:
from numpy import array,zeros
A=array([[5, -3, 0], [-3, 9, -6], [0, -6, 10]], float)
print(A)
b=array([5,4,1], float)
def Gauss_Elim(A,b): #defines the function
    N = len(b) #defines N as the length of b
    #print(N) #prints N
    for m in range(N): #creates a for loop to iterate N times
        div = A[m,m] #divides by the diagonal
        b[m] /= div 
        A[m,:] /= div 
        for i in range(m+1,N): #creates a for loop to itereate from m+1 to N
            mult = A[i,m] #subtracts from the lower rows
            b[i] -= mult*b[m]
            A[i,:] -= mult*A[m,:]
    return A,b #gives result
Asol , bsol  = Gauss_Elim(A,b)
print(Asol)
print(bsol)

[[  5.  -3.   0.]
 [ -3.   9.  -6.]
 [  0.  -6.  10.]]
[[ 1.         -0.6         0.        ]
 [ 0.          1.         -0.83333333]
 [ 0.          0.          1.        ]]
[ 1.          0.97222222  1.36666667]


In [9]:
def Back_Sub(A,b): #defines the function
    N = len(b) #defines N as the length of b
    x = zeros(N,float) #creates an array of N zeros
    x[N-1] = b[N-1] 
    for m in range(N-1,-1,-1): #creates for loop to iterate through N-1 to -1 backwards
        x[m] = b[m]#backsubstitution
        for i in range(m+1,N):
            x[m] -= A[m,i]*x[i]
    return x
print(Back_Sub(A,b))

[ 2.26666667  2.11111111  1.36666667]


## Questions:
    1) What are the benefits of using the algorithm as opposed to solving by hand?
    2) How can this code fail?

In [ ]:
#1) It's much faster and it stores the matrices so you can easily use them later. Also once you have the algorithm,
#you can manipulate it for more problems without rewriting everything.
#2) There is no easy way to tell if something is wrong in the code until after we calculate everything.